server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml      #mybatis 配置路径
  type-aliases-package: com.microservice.springcloud.entity     #所有entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                   #mapper映射文件

spring:
  application:
    name: microservicecloud-blog
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource          #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver            #mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb01                 #url
    username: root
    password: root
    dbcp2:
      min-idle: 5                                         #数据库最小连接数
      initial-size: 5                                     #初始化连接数
      max-total: 5                                        #最大连接数
      max-wait-millis: 200                                #等待连接获取最大超时时间
      test-while-idle: true                               #空闲时是否进行连接测试（默认true）
      validation-query-timeout: 20000
      validation-query: SELECT 1
  devtools:
    livereload:
      port: 35737
    remote:
      restart:
        enabled: false
    add-properties: true                                  #开发者工具 热部署
eureka:
  instance:
    instance-id: microservice-hystrix #映射名称
    prefer-ip-address: true #访问路径可以显示ip地址
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#      defaultZone: http://localhost:7001/eureka

info:
  app.name: blog-microsoftcloud
  company.name: www.microsoftcloud.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
