server:
  port: 3344

spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaoxiongxiong/microservice-config.git  #git远程仓库名称
        #uri: git@192.168.242.129:/home/gitrepo/microservice-config.git  #git远程仓库名称

